/*
 * ShadyCraft © 2014
 */
package dicetrials;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintStream;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/*
 * @author Shady Ibrahim
 */
public class DiceTrials extends javax.swing.JFrame {

    /*
     * Creates new form DiceTrials
     */
    public DiceTrials() {
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch(Exception e)
        {
            System.out.println("Look and feel");
        }        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainGroup = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblDiceNumber2 = new javax.swing.JLabel();
        lblOrDice = new javax.swing.JLabel();
        lblNumber1 = new javax.swing.JLabel();
        jBoxDie1 = new javax.swing.JComboBox();
        jBoxDie2 = new javax.swing.JComboBox();
        lblRunUntil = new javax.swing.JLabel();
        lblInArow = new javax.swing.JLabel();
        txtInArow = new javax.swing.JTextField();
        lblDiceRollsTitle = new javax.swing.JLabel();
        txtHowMany = new javax.swing.JTextField();
        lblTrialsComplete = new javax.swing.JLabel();
        lblOrRunUntil = new javax.swing.JLabel();
        txtSuccess = new javax.swing.JTextField();
        lblSuccess = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        btnBegin = new javax.swing.JButton();
        rdoSuccess = new javax.swing.JRadioButton();
        rdoTrials = new javax.swing.JRadioButton();
        imgMainGIF = new javax.swing.JLabel();
        btnInstructions = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        lblTitle.setText("Shady's Dice Simulator");

        lblDiceNumber2.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        lblDiceNumber2.setText("Number 2:");

        lblOrDice.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblOrDice.setText("Or a...");

        lblNumber1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        lblNumber1.setText("Number 1:");

        jBoxDie1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jBoxDie2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        lblRunUntil.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblRunUntil.setText("Run until...");

        lblInArow.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblInArow.setText("times In a row.");

        lblDiceRollsTitle.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblDiceRollsTitle.setText("Dice Roll Must equal a...");

        lblTrialsComplete.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblTrialsComplete.setText("trials complete.");

        lblOrRunUntil.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblOrRunUntil.setText("Or...");

        lblSuccess.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblSuccess.setText("trial(s) successful.");

        lblResult.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblResult.setText("Result:");

        btnBegin.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnBegin.setText("Run Trials");
        btnBegin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeginActionPerformed(evt);
            }
        });

        mainGroup.add(rdoSuccess);

        mainGroup.add(rdoTrials);

        imgMainGIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dicetrials/images/animated-dice-image-0020.gif"))); // NOI18N

        btnInstructions.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnInstructions.setText("Instructions");
        btnInstructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstructionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBegin, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDiceNumber2)
                        .addGap(18, 18, 18)
                        .addComponent(jBoxDie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155)
                        .addComponent(rdoSuccess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSuccess, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(imgMainGIF)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblSuccess)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInstructions)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblOrDice)
                        .addGap(304, 304, 304)
                        .addComponent(lblOrRunUntil))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtInArow, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblInArow)
                        .addGap(101, 101, 101)
                        .addComponent(lblResult))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNumber1)
                                .addGap(18, 18, 18)
                                .addComponent(jBoxDie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDiceRollsTitle))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRunUntil)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoTrials)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHowMany, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(lblTrialsComplete)))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTitle)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiceRollsTitle)
                    .addComponent(lblRunUntil))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumber1)
                    .addComponent(jBoxDie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTrialsComplete)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rdoTrials)
                                .addComponent(txtHowMany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrDice)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblOrRunUntil)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSuccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSuccess)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDiceNumber2)
                                    .addComponent(jBoxDie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(txtInArow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblInArow)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblResult))))
                    .addComponent(rdoSuccess))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBegin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imgMainGIF))
                    .addComponent(btnInstructions, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBeginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeginActionPerformed
        PrintStream printer = null;
        try {
            int num1 = jBoxDie1.getSelectedIndex() + 2;
            int num2 = jBoxDie2.getSelectedIndex() + 2;
            int pwin = 0, ptotal = 0, trials = 0;
            Random random = new Random();
            File theTrials = new File("Trials.docx");
            printer = new PrintStream(theTrials);
            if(rdoSuccess.isSelected())           
            {
                for(int i = 0; i < Integer.parseInt(txtSuccess.getText()); i++)
                {
                    pwin = 0;
                    while(Integer.parseInt(txtInArow.getText()) != pwin)
                    {
                        int die1 = 1 + random.nextInt((6 - 1) + 1);
                        int die2 = 1 + random.nextInt((6 - 1) + 1);
                        
                        printer.println(die1 + " + " + die2 + " = " +  (die1 + die2));
                        
                        if(die1 + die2 == num1 || die1 + die2 == num2)
                        {
                            pwin++;
                        }
                        else
                        {
                            pwin = 0;
                        }
                        trials++;
                    }
                    ptotal++;
                }
                lblResult.setText("<html>Result: <b><font color=\"red\">" + txtSuccess.getText() +  "</b></font></br> out of <b><font color=\"red\">" + trials + "</b></font> trials met the sepcified criteria.");
            }
            else if(rdoTrials.isSelected())
            {
                for(int i = 0; i < Integer.parseInt(txtHowMany.getText()); i++)
                {
                    int die1 = 1 + random.nextInt((6 - 1) + 1);
                    int die2 = 1 + random.nextInt((6 - 1) + 1);
                    
                    if(die1 + die2 == num1 || die1 + die2 == num2)
                    {
                        pwin++;                       
                        if(pwin == Integer.parseInt(txtInArow.getText()))
                        {
                            ptotal++;
                            pwin = 0;
                        }
                    }
                    else
                    {
                        pwin = 0;
                    }                        
                    trials++;
                }
                lblResult.setText("<html>Result: <b><font color=\"red\">" + ptotal +  "</b></font></br> out of <b><font color=\"red\">" + trials + "</b></font> trials met the sepcified criteria.");                                
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DiceTrials.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            printer.close();                                        
        }
    }//GEN-LAST:event_btnBeginActionPerformed

    private void btnInstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstructionsActionPerformed
        
        new Instructions().setVisible(true);
        
    }//GEN-LAST:event_btnInstructionsActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiceTrials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiceTrials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiceTrials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiceTrials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiceTrials().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBegin;
    private javax.swing.JButton btnInstructions;
    private javax.swing.JLabel imgMainGIF;
    private javax.swing.JComboBox jBoxDie1;
    private javax.swing.JComboBox jBoxDie2;
    private javax.swing.JLabel lblDiceNumber2;
    private javax.swing.JLabel lblDiceRollsTitle;
    private javax.swing.JLabel lblInArow;
    private javax.swing.JLabel lblNumber1;
    private javax.swing.JLabel lblOrDice;
    private javax.swing.JLabel lblOrRunUntil;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblRunUntil;
    private javax.swing.JLabel lblSuccess;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTrialsComplete;
    private javax.swing.ButtonGroup mainGroup;
    private javax.swing.JRadioButton rdoSuccess;
    private javax.swing.JRadioButton rdoTrials;
    private javax.swing.JTextField txtHowMany;
    private javax.swing.JTextField txtInArow;
    private javax.swing.JTextField txtSuccess;
    // End of variables declaration//GEN-END:variables
}
