/*
 * ShadyCraft © 2014
 */
package dicetrials;

import java.util.Random;
import javax.swing.UIManager;

/*
 * @author Shady Ibrahim
 */
public class DiceTrials extends javax.swing.JFrame {

    /*
     * Creates new form DiceTrials
     */
    public DiceTrials() {
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch(Exception e)
        {
            System.out.println("Look and feel");
        }        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainGroup = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblDiceNumbers = new javax.swing.JLabel();
        lblDiceNumbers1 = new javax.swing.JLabel();
        lblDiceNumbers2 = new javax.swing.JLabel();
        jBoxDie1 = new javax.swing.JComboBox();
        jBoxDie2 = new javax.swing.JComboBox();
        lblDiceNumbers3 = new javax.swing.JLabel();
        lblDiceNumbers4 = new javax.swing.JLabel();
        txtInArow = new javax.swing.JTextField();
        lblDiceNumbers5 = new javax.swing.JLabel();
        txtHowMany = new javax.swing.JTextField();
        lblDiceNumbers6 = new javax.swing.JLabel();
        lblDiceNumbers7 = new javax.swing.JLabel();
        txtSuccess = new javax.swing.JTextField();
        lblDiceNumbers9 = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rdoSuccess = new javax.swing.JRadioButton();
        rdoTrials = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        lblTitle.setText("Shady's Dice Simulator");

        lblDiceNumbers.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        lblDiceNumbers.setText("Number 2:");

        lblDiceNumbers1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblDiceNumbers1.setText("Or a...");

        lblDiceNumbers2.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        lblDiceNumbers2.setText("Number 1:");

        jBoxDie1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jBoxDie2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        lblDiceNumbers3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblDiceNumbers3.setText("Run until...");

        lblDiceNumbers4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblDiceNumbers4.setText("times In a row.");

        lblDiceNumbers5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblDiceNumbers5.setText("Dice Roll Must equal a...");

        lblDiceNumbers6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblDiceNumbers6.setText("trials complete.");

        lblDiceNumbers7.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblDiceNumbers7.setText("Or...");

        lblDiceNumbers9.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblDiceNumbers9.setText("trial(s) successful.");

        lblResult.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblResult.setText("Result:");

        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jButton1.setText("Run Trials");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mainGroup.add(rdoSuccess);

        mainGroup.add(rdoTrials);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dicetrials/images/animated-dice-image-0020.gif"))); // NOI18N

        jButton2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jButton2.setText("Instructions");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDiceNumbers)
                        .addGap(18, 18, 18)
                        .addComponent(jBoxDie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(243, 243, 243))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(lblTitle)
                .addContainerGap(192, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiceNumbers1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtInArow, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblDiceNumbers4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDiceNumbers2)
                        .addGap(18, 18, 18)
                        .addComponent(jBoxDie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDiceNumbers5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdoSuccess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSuccess, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblDiceNumbers9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblDiceNumbers7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblResult))
                    .addComponent(lblDiceNumbers3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdoTrials)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHowMany, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblDiceNumbers6)))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTitle)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDiceNumbers5)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiceNumbers2)
                            .addComponent(jBoxDie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(lblDiceNumbers1)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiceNumbers)
                            .addComponent(jBoxDie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(txtInArow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDiceNumbers4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDiceNumbers3)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiceNumbers6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rdoTrials)
                                .addComponent(txtHowMany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addComponent(lblDiceNumbers7)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSuccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDiceNumbers9))
                                .addGap(29, 29, 29)
                                .addComponent(lblResult))
                            .addComponent(rdoSuccess))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int num1 = jBoxDie1.getSelectedIndex() + 2;
        int num2 = jBoxDie2.getSelectedIndex() + 2;
        int pwin = 0, ptotal = 0, trials = 0;
        Random random = new Random();        
        
        if(rdoSuccess.isSelected())
        {
            for(int i = 0; i < Integer.parseInt(txtSuccess.getText()); i++)           
            {
                pwin = 0;
                while(Integer.parseInt(txtInArow.getText()) != pwin)
                {
                    int die1 = 1 + random.nextInt((6 - 1) + 1);
                    int die2 = 1 + random.nextInt((6 - 1) + 1);

                    if(die1 + die2 == num1 || die1 + die2 == num2)
                    {
                        pwin++;                       
                    }
                    else
                    {
                        pwin = 0;
                    }                                       
                    trials++;
                }
                ptotal++;                                
            }
            lblResult.setText("<html>Result: <b><font color=\"red\">" + txtSuccess.getText() +  "</b></font></br> out of <b><font color=\"red\">" + trials + "</b></font> trials met the sepcified criteria.");                            
        }
        else if(rdoTrials.isSelected())
        {
            for(int i = 0; i < Integer.parseInt(txtHowMany.getText()); i++)           
            {
                int die1 = 1 + random.nextInt((6 - 1) + 1);
                int die2 = 1 + random.nextInt((6 - 1) + 1);

                if(die1 + die2 == num1 || die1 + die2 == num2)
                {
                    pwin++;
                    if(pwin == Integer.parseInt(txtInArow.getText()))
                    {
                        ptotal++;
                        pwin = 0;
                    }
                }
                else
                {
                    pwin = 0;
                }                                       
                trials++;                        
            }
            lblResult.setText("<html>Result: <b><font color=\"red\">" + ptotal +  "</b></font></br> out of <b><font color=\"red\">" + trials + "</b></font> trials met the sepcified criteria.");                                        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        new Instructions().setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiceTrials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiceTrials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiceTrials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiceTrials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiceTrials().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jBoxDie1;
    private javax.swing.JComboBox jBoxDie2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDiceNumbers;
    private javax.swing.JLabel lblDiceNumbers1;
    private javax.swing.JLabel lblDiceNumbers2;
    private javax.swing.JLabel lblDiceNumbers3;
    private javax.swing.JLabel lblDiceNumbers4;
    private javax.swing.JLabel lblDiceNumbers5;
    private javax.swing.JLabel lblDiceNumbers6;
    private javax.swing.JLabel lblDiceNumbers7;
    private javax.swing.JLabel lblDiceNumbers9;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblTitle;
    private javax.swing.ButtonGroup mainGroup;
    private javax.swing.JRadioButton rdoSuccess;
    private javax.swing.JRadioButton rdoTrials;
    private javax.swing.JTextField txtHowMany;
    private javax.swing.JTextField txtInArow;
    private javax.swing.JTextField txtSuccess;
    // End of variables declaration//GEN-END:variables
}
